### ISSUE TITLE
Update docker version

### ISSUE THREAD

**Issue by benmoss** [cloudfoundry/windows-tools-release#12]
We're trying to use docker with Kubernetes and are running into an issue where the version that's supplied here is now too old for the Docker client library used in k8s. We found this updated version via the MicrosoftDockerProvider Powershell installer, can you update to it? I'd send a PR but bosh blobs don't lend themselves to PRs.

https://dockermsft.blob.core.windows.net/dockercontainer/docker-18-03-1-ee-4.zip

**Comment by benmoss** [comment]
It turns out that that docker version is also too old. We tried https://dockermsft.blob.core.windows.net/dockercontainer/docker-18-09-0.zip and it works on our 1803 vm as far as we can tell, and has the version we need (API version >= 1.38)

**Comment by natalieparellano** [comment]
@benmoss it looks like that zip file has the following directory structure:
```
docker\docker.exe
docker\dockerd.exe
docker\libeay32.dll
docker\libwinpthread-1.dll
docker\licenses.txt
docker\ssleay32.dll
docker\vcruntime140.dll
docker/
docker/docker.exe
docker/dockerd.exe
```

The duplicate docker*.exe are causing the compilation step to fail. Which one do you need?

**Comment by benmoss** [comment]
We asked someone at Docker about that and they acknowledged that the duplication was a bug, so there's a chance it will be fixed, but probably not until the next release. They told us to just use the forward slash versions.

**Comment by benmoss** [comment]
I created a new version of that zip file here: https://storage.googleapis.com/ben-kops/docker-18-09-0.zip

```
$ unzip -l ~/Downloads/docker-18-09-0.zip
Archive:  /home/ben/Downloads/docker-18-09-0.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2018-12-20 09:50   docker/
 64156232  2018-11-07 18:22   docker/docker.exe
 70659144  2018-11-07 18:22   docker/dockerd.exe
---------                     -------
134815376                     3 files
```

**Comment by natalieparellano** [comment]
Thanks Ben! We actually tried doing that, but it looks like the dlls in the zipfile are also required for docker to work. We made a new zipfile that includes those executables plus the dlls and it seems to work. 

We cut a new version (v32) of this release that has those changes.

**Comment by benmoss** [comment]
@natalieparellano I checked it out and it looks like it works! Thanks!
