### ISSUE TITLE
Path for go-1.12.5

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/windows-tools-release#20]
Hi,

Thanks for bumping golang. However, when we deployed a windows worker in concourse, it failed to find `go` in the path.

SSHing onto the worker, we see path is
```
PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\GooGet;C
:\Program Files\Google\Compute Engine\metadata_scripts;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program F
iles\Google\Compute Engine\sysprep;C:\var\vcap\bosh\bin;C:\var\vcap\packages\mingw64\mingw64\bin;c:\var\vcap\packages\git\bin;C:
\var\vcap\packages\golang-windows\go\bin
```

But golang binary is installed in \var\vcap\packages\golang-1.12-windows\go\bin though so it's not in the path.

Maybe you need to update https://github.com/cloudfoundry/windows-tools-release/blob/ea31a6e61616334c384a7a197b8778eec8351021/jobs/golang-windows/templates/pre-start.ps1#L10?

Thanks,

Kieron and Danail (from Garden).

**Comment by achasveachas** [comment]
Fixed in release v43.

https://github.com/cloudfoundry/windows-tools-release/releases/tag/v43
