### ISSUE TITLE
golang-1-windows job is not included in the release

### ISSUE THREAD

**Issue by TisVictress** [cloudfoundry/windows-tools-release#26]
We were not able to specify the latest golang-1 dependency within our bosh manifest.  We're getting the following error:

`Task 23984 | 20:14:09 | Error: Job 'golang-1-windows' not found in Template table`

We are using version 58

**Comment by genevieve** [comment]
Hey! Could you include the section of your manifest that specifies the windows-tools-release version + job configuration? We are not seeing this issue in our different environments when deploying with v58 of this release with the golang-1-windows job so would like to compare our manifests.

**Comment by genevieve** [comment]
For instance, in ours it says:
```
...
- name: golang-1-windows
  release: windows-tools
...
- name: "windows-tools"
  version: "58"
  url: "https://bosh.io/d/github.com/cloudfoundry-incubator/windows-tools-release?v=58"
  sha1: "285ec9eb53c889cef262b0252e9b7e81ef6b002d"
```

**Comment by genevieve** [comment]
Hey!

Skip v58 and jump to either v59 or v60.

```
- name: "windows-tools"
  version: "60"
  url: "https://bosh.io/d/github.com/cloudfoundry-incubator/windows-tools-release?v=60"
  sha1: "57f40aab20be5868d0ed2e9d55228484ca901046"
```
