### ISSUE TITLE
Please release

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/windows-tools-release#28]
Hello,

Last windows-tools release (v68) is more than half a year old. I can see that there have been automatic bumps of golang since then but we (CF Garden) cannot make use of them. Could you please pull a release for us?

Thank you!

**Comment by mvalliath** [comment]
Hi @danail-branekov.

We released [v69](https://github.com/cloudfoundry/windows-tools-release/releases/tag/v69) of the Windows Tools Release today. Please let us know if you need anything else!

Thanks!
Malini

**Comment by aemengo** [comment]
@danail-branekov Forgive me, but I have to wonder why you're relying on this release for Golang updates. A better source of truth would be **bosh-packages/golang-release**.

https://github.com/bosh-packages/golang-release

**Comment by danail-branekov** [comment]
Hey @aemengo 

We use the `windows-tools-release` in the windows worker of our concourse CI. When we bump golang in Garden, we want to make sure that all Garden binaries can be compiled and work correctly with the Golang version we bump to, that is why we need that Golang version on the windows worker. To put it in other way, this is not a compile-time dependency of ours, we just want to have that golang version available on the worker so that the worker compiles the Garden binaries with it.

Our CI configuration is in a private repo but here is how we configure the golang version:

```
- type: replace
  path: /instance_groups/name=windows-worker/jobs/-
  value:
    name: golang-1-windows
    release: windows-tools
```

We have been been getting windows golang updates like that for ages, if using the `bosh-packages/golang-release` is the proper way to do that, we would be happy to switch. I will file a chore in our backlog to look into that.

Thanks!
