### ISSUE TITLE
Cut release for golang 1.18

### ISSUE THREAD

**Issue by jpalermo** [cloudfoundry/windows-tools-release#30]
The `golang-1-windows` was recently bumped to golang 1.18 [here](https://github.com/cloudfoundry/windows-tools-release/commit/3f81c7d28f0f7656f1ef20a52d189d693e69d03d), could we get a new final release cut with these changes?

Thanks!

**Comment by selzoc** [comment]
https://github.com/cloudfoundry/windows-tools-release/releases/tag/v73 has been released.
