### ISSUE TITLE
Bump Golang to 1.9.4

### ISSUE THREAD

**Issue by craigfurman** [cloudfoundry/windows-tools-release#6]
Hi there!

Would you be able to please bump golang in this release to 1.9.4? I would PR the change myself but I'm unable to bosh upload-blobs to your bucket :(

Thanks!

**Comment by sunjayBhatia** [comment]
@craigfurman final release with golang 1.9.4 here: https://github.com/cloudfoundry-incubator/windows-tools-release/releases/tag/v5 should be on bosh.io soon

**Comment by craigfurman** [comment]
legendarily fast turnaround. Thanks @sunjayBhatia !
